# Generated by Django 4.0.4 on 2022-04-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provincias', '0002_ciudad'),
        ('donantes', '0001_initial'),
        ('instituciones', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pacientes',
            new_name='Paciente',
        ),
        migrations.CreateModel(
            name='ReposicionesAsignadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReposicionElegida', models.DateField()),
                ('comentario', models.TextField(max_length=1024)),
                ('idDonante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donantes.donante')),
                ('idPaciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.paciente')),
            ],
        ),
    ]
